#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash

############################################       R E A D  M E      ######################################################
## Built on UGE 8.6.4. The code may need editing if you are working with a different grid engine
## This code will run smMIP_level_raw_and_consensus_pileups.R for every sample_clean.bam file generated by map_smMIPs_extract_UMIs.R
## Only the mandatory parameters are used. If you want to change the defaults, you must add your changes to the code below.
## This code file needs to be in the same folder as smMIP_level_raw_and_consensus_pileups.R to work properly.
## It also assume that your folder structure is the same as the one that will be generated by following the example in the manual
###########################################################################################################################

#Enter the path to the directory containing the bam files
BAM=/.mounts/labs/abelsonlab/private/smMIP_ARCH/CODE/example_github/Example/bams/  #CHANGE HERE (this is the folder that supposed to contain all the initial bam files)

#Enter the path to the smMIP-design file
TARGET=/.mounts/labs/abelsonlab/private/smMIP_ARCH/CODE/example_github/Example/supplemental_files/Target_MIPgen.txt  #CHANGE HERE


for file in $( ls $BAM/*/*clean.bam ); do

        ### GENERATING THE SCRIPT
        SAMPLE=$(basename $(echo $file | sed 's/_clean.bam.*//'))  #Please note the sample name is extracted from the clean bam file name. Assumed to be sample_clean.bam 
        echo -e "#!/bin/bash -l\n#$ -S /bin/bash\n#$ -cwd\n\n" > automatic_script_for_smMIP_level_raw_and_consensus_pileups_$SAMPLE.sh
        echo -e "module load rstats/3.6\n" >> automatic_script_for_smMIP_level_raw_and_consensus_pileups_$SAMPLE.sh #Loading R. Delete this line if R is rooted. Change the module name to your R module if it isnt.
        echo -e "Rscript smMIP_level_raw_and_consensus_pileups.R -b $file -p $TARGET" >> automatic_script_for_smMIP_level_raw_and_consensus_pileups_$SAMPLE.sh

        ### RUNNING THE SCRIPT
        qsub -P abelsonlab -l h_vmem=16g automatic_script_for_smMIP_level_raw_and_consensus_pileups_$SAMPLE.sh

done